### ISSUE TITLE
There is a problem with the dist folder 

### ISSUE THREAD

**Issue by coldSeattle** [whimelan/Gulp4-starter#1]
when I layout in the app and there I write image paths relative to the pug files, but these paths do not change in the dist folder in Index.html. And in
  GitHub Pages the  pictures are not loaded, and I had to manually delete the points (. And why else just like that in the app index.html if it is not used?

**Comment by whimelan** [comment]
I have noticed unnecessary files in app folder some time ago, but I was lazy to fix it, now you have prompted me to fix that :) 
Also I wanted to update my repo to fix issues with paths to images, thank you for comment, I'll solve this problem as soon as possible! 

Feel free to ask me about my repo, and thanks for using it ;)

**Comment by coldSeattle** [comment]
thank you!
