### ISSUE TITLE
Also you can update your README.md file to up-to-date.

### ISSUE THREAD

**Issue by coldSeattle** [whimelan/Gulp4-starter#2]
You changed the file structure and you also can update the README.md to up-to-date.

**Comment by coldSeattle** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/56102448/78376866-92d3e480-75d7-11ea-91b8-a22b45dc58e4.png)
![Screenshot_2](https://user-images.githubusercontent.com/56102448/78376867-936c7b00-75d7-11ea-8c8d-23647e1255f1.png)

**Comment by whimelan** [comment]
Thank you! I was fixing this problem, now I updated README and you can use it with all advantages! ;)

**Comment by coldSeattle** [comment]
thanks!
